apiVersion: v1
kind: Pod
metadata:
  name: runner-worker-pod
  labels:
    app: code-executor
spec:
  volumes:
    - name: workspace-volume
      emptyDir: {}

  initContainers:
    - name: init-r2-downloader
      image: amazon/aws-cli
      command:
        - sh
        - -c
        - |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && \
          aws configure set default.region us-east-1 && \
          aws s3 cp s3://replit/code/67f92b9e2caf4b63892a93f8/680a691e3de843ff0e22ee33/ /workspace/ --recursive --endpoint-url https://4ea86ca138a9f14ac92232c42ba24b37.r2.cloudflarestorage.com

      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: r2-secret
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: r2-secret
              key: secret_key
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace

  containers:
    - name: runner
      image: piyushgpt/repl-runner
      ports:
        - containerPort: 3001
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"

    - name: worker
      image: piyushgpt/repl-worker
      ports:
        - containerPort: 3002
        - containerPort: 5173
      volumeMounts:
        - name: workspace-volume
          mountPath: /workspace
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=768"
