apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codefluxcloud-in
  namespace: default
spec:
  secretName: codefluxcloud-in-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: codefluxcloud.in
  dnsNames:
  - "*.codefluxcloud.in"
  - codefluxcloud.in
