# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: your-registry/frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value:  "https://api.codeflux.com"
        - name: VITE_POD_DEPLOYMENT_URL
          value: "https://poddeployment.codeflux.com"
        - name: VITE_WS_URL
          value: "wss://api.codeflux.com"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 5173
    targetPort: 5173
  type: LoadBalancer