# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: piyushgpt/repl-frontend:77cc6c3eef5c68ebf28b4c76b1e92a171ecb6315
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "8Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: codeflux-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer