apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeflux-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - "codeflux.com"
    - "www.codeflux.com"
    - "api.codeflux.com"
    - "poddeployment.codeflux.com"
    secretName: codeflux-tls
  rules:
  - host: codeflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 5173
  - host: www.codeflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 5173
  - host: api.codeflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server
            port:
              number: 3000
  - host: poddeployment.codeflux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poddeployment
            port:
              number: 4001