# poddeployment-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poddeployment
  labels:
    app: poddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poddeployment
  template:
    metadata:
      labels:
        app: poddeployment
    spec:
      serviceAccountName: poddeployment-sa
      containers:
      - name: poddeployment
        image: piyushgpt/repl-pod-deployment:77cc6c3eef5c68ebf28b4c76b1e92a171ecb6315
        ports:
        - containerPort: 4001
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        envFrom:
        - secretRef:
            name: codeflux-secrets
        - configMapRef:
            name: codeflux-config
        resources:
          requests:
            memory: "80Mi"
            cpu: "10m"
          limits:
            memory: "160Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: poddeployment
spec:
  selector:
    app: poddeployment
  ports:
  - port: 4001
    targetPort: 4001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poddeployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poddeployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70