# poddeployment-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poddeployment
  labels:
    app: poddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poddeployment
  template:
    metadata:
      labels:
        app: poddeployment
    spec:
      serviceAccountName: poddeployment-sa
      containers:
      - name: poddeployment
        image: piyushgpt/repl-pod-deployment:86bac0595f4c32126e95c83753963ef8519c3a8a
        ports:
        - containerPort: 4001
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        envFrom:
        - secretRef:
            name: codeflux-secrets
        - configMapRef:
            name: codeflux-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: poddeployment
spec:
  selector:
    app: poddeployment
  ports:
  - port: 4001
    targetPort: 4001
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poddeployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poddeployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70